abbreviations = {
# from observation
'frt' : 'fruit',
'whl' : 'whole',
'i/cream' : 'ice cream',
'unslt' : 'unsalted',
'cashw' : 'cashew',
'pst' : 'paste',
'swt': 'sweetened',
'choc' : 'chocolate',
's/skim' : 'semi skimmed',
'chse' : 'cheese',
'chse/tom' : 'cheese and tomato',
'/' : ' and ',
'k/towels' : 'kitchen towels',
# colours
"blk": "black",
"wht": "white",
"gry": "gray",
"slv": "silver",
"red": "red",
"org": "orange",
"yel": "yellow",
"grn": "green",
"blu": "blue",
"pur": "purple",
"brn": "brown",
"bge": "beige",
"pnk": "pink",
"gld": "gold",
# other suggestions
"zinfan": "Zinfandel",
"tkk": "Tikka",
"msla": "Masala",
"sce": "Sauce",
"lg": "Large",
"sm": "Small",
"reg": "Regular",
"med": "Medium",
"lite": "Light",
"dk": "Dark",
"pcs": "Pieces",
"kg": "Kilogram",
"gm": "Gram",
"ml": "Milliliter",
"cl": "Centiliter",
"l": "Liter",
"oz": "Ounce",
"lb": "Pound",
"gal": "Gallon",
"chzbrgr": "Cheeseburger",
"lttlsmln": "Littleneck Clams",
"chccp": "Chocolate Chip Cookies",
"rspbry": "Raspberry",
"grnprcn": "Green Peppers",
"rnchdrsg": "Ranch Dressing",
"itlnssg": "Italian Sausage",
"fznyg": "Frozen Yogurt",
"crnflk": "Corn Flakes",
"bcn": "Bacon",
"crls": "Cereal",
"fdprcsr": "Food Processor",
"grnpst": "Green Pesto",
"ckis": "Cookies",
"lbstr": "Lobster",
"flr": "Flour",
"grlc": "Garlic",
"smlg": "Smoked Salmon",
"gngr": "Ginger",
"srm": "Serum",
"chspzza": "Cheese Pizza",
"fznblubry": "Frozen Blueberries",
"bnlssknls": "Boneless Skinless Chicken",
"whtrce": "White Rice",
"grnbns": "Green Beans",
"hnymst": "Honey Mustard",
"wldrce": "Wild Rice",
"vgtblsd": "Vegetable Salad",
"fldbf": "Flank Steak",
"orgcarrots": "Organic Carrots",
"grnpprstpfr": "Green Pepper Steak Fry",
"spcyssnng": "Spicy Seasoning",
"cntrcutpork": "Center Cut Pork",
"bnlsprtbllo": "Boneless Portobello",
"grnditlnssg": "Ground Italian Sausage",
"hrbs": "Herbs",
"pkldbttr": "Pickled Butter",
"hnywhtbrd": "Honey Wheat Bread",
"srfl": "Surfactant",
"hrrstchkn": "Herb Roasted Chicken",
"yog": "yogurt",
"mlk": "milk",
"choc": "chocolate",
"psta": "pasta",
"rce": "rice",
"bnlsbf": "boneless beef",
"srdn": "sardines",
"stpmxn": "steakhouse potato mix",
"grnpppr": "green pepper",
"mshrm": "mushroom",
"sls": "sausage links",
"syrp": "syrup",
"pncake": "pancake",
"wflcone": "waffle cone",
"chpdip": "chip dip",
"slt": "salt",
"ppr": "pepper",
"dspnsr": "dispenser",
"clnr": "cleaner",
"hyg": "hygiene",
"coke": "coca-cola or any other coca-cola company beverage",
"pepsi": "pepsi-cola or any other pepsico beverage",
"oj": "orange juice",
"pbj": "peanut butter and jelly",
"pb": "peanut butter",
"j": "jelly",
"ktchp": "ketchup",
"mayo": "mayonnaise",
"spgh": "spaghetti",
"mtloaf": "meatloaf",
"chckn": "chicken",
"grdbeef": "ground beef",
"tuna": "canned tuna",
"bnlschk": "boneless chicken",
"hmbgr": "hamburger",
"hotdg": "hotdog",
"fries": "french fries",
"chs": "cheese",
"bnlspork": "boneless pork",
"brd": "bread",
# fruit and vegetable soup
"app": "apple",
"avoc": "avocado",
"ban": "banana",
"bellpep": "bell pepper",
"broc": "broccoli",
"carrot": "carrot",
"cel": "celery",
"corn": "corn",
"cuc": "cucumber",
"grape": "grape",
"grapefr": "grapefruit",
"grnbean": "green bean",
"kiwi": "kiwi",
"lem": "lemon",
"lett": "lettuce",
"lime": "lime",
"mango": "mango",
"melon": "melon",
"onion": "onion",
"orange": "orange",
"peach": "peach",
"pear": "pear",
"pineapp": "pineapple",
"plum": "plum",
"potato": "potato",
"spin": "spinach",
"sqsh": "squash",
"strawb": "strawberry",
"tom": "tomato",
"waterm": "watermelon",
'bro' : 'broccoli',
'cor' : 'corriander',
'car' : 'carrot'
}

def remove_abbreviations(text: str) -> str:
    text = text.split(' ')
    out = ''

    for i in range(len(text)):
        if abbreviations.get(text[i]) != None:
            out += abbreviations[text[i]] + ' '
        else:
            out += text[i] + ' '
    return out
